spring.application.name=torneo-calcio
# Connessione al Database
spring.datasource.url=jdbc:postgresql://localhost:5432/siw-progetto-torneo
spring.datasource.username=postgres
spring.datasource.password=erlollus

# Configurazione JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true